### PR TITLE
Added hardcoded OCPP availability switch

### PR DESCRIPTION
**Pull request by andreasropel**
Please check following lines if I missed anything:
89
100
101
102
112

### CODE REVIEW

**Comment by elden1337** [comment]
Thanks! Im away til Monday evening so no action before then probably.

**Review by elden1337 — APPROVED** [review]

**Comment by elden1337** [comment]
However, with this set, you should be able to test install. Just one problem, if you compare config_flow.py from this branch with main you'll see diff that i made recently but forgot to merge to this branch. So you wont be able to go through setup without manually doing that, or wait til next week.

**Comment by andreasropel** [comment]
I’ll wait. No worries.

**Comment by elden1337** [comment]
merged PR and pushed merge from main to get latest fixes.

**Pull request merged**
