### PR TITLE
Misc changes for Garo wallbox

### PR DESCRIPTION
**Pull request by joek-makewave**

### CODE REVIEW

**Comment by elden1337** [comment]
i'll merge this now. but are you 100% sure that `"charging paused" # charging disabled by load balancer` shouldn't be under ChargeControllerStates.Connected ?

**Comment by elden1337** [comment]
ref #7 this should fix the merepart of it.

**Comment by joek-makewave** [comment]
> i'll merge this now. but are you 100% sure that `"charging paused" # charging disabled by load balancer` shouldn't be under ChargeControllerStates.Connected ?

No, not sure. You know better what state 'Idle' is. But I think that 'charging paused' it is different from 'charging disabled' where charging is possible but disabled by Peaqev or the user. No use for Peaqev to try to start while state is 'charging paused'.

**Comment by joek-makewave** [comment]
I'll continue testing from develop and later on from main when it is available there. Thank you for your work!

**Comment by elden1337** [comment]
Idle = car is not connected to charger
That's why i'm wondering about that state. 

Let it run for a bit (expensive days ahead so perhaps not that much charging) and let me know.

**Comment by elden1337** [comment]
working well for you so far? @joek-makewave

**Comment by elden1337** [comment]
ok not good. 
what kind of issues are we talking about? unreachable sensors or other stuff?

**Comment by joek-makewave** [comment]
There are errors, maybe not important
```
2023-06-21 00:04:43.669 ERROR (MainThread) [homeassistant.components.filter.sensor] Could not convert state:  (<class 'str'>) to number
2023-06-21 01:02:05.079 ERROR (MainThread) [custom_components.peaqev.peaqservice.hub.max_min_controller] Encountered problem when trying to reset max charge to normal: could not convert string to float: 'unavailable'
```
Last time I got the impression that there were more errors in develop compared to the older garo_wallbox. And that it was difficult to get peaqev to go to Start and start charging. But I'm not sure, maybe it is the same, and the main problem I have might be that in many use cases it is necessary to reload the integration to get it out of the "running" state so that it will do a second start charging.

I will hopefully learn more as I continue using it.

A problem with Garo is that it takes very long for the 'charging power' and 'charging current' sensors to go to zero when charging is stopped. For Garo it would be better to track 'active' by checking the state. The state goes to "charging disabled" a lot quicker than power and current goes to zero.

**Comment by elden1337** [comment]
> There are errors, maybe not important
> 
> ```
> 2023-06-21 00:04:43.669 ERROR (MainThread) [homeassistant.components.filter.sensor] Could not convert state:  (<class 'str'>) to number
> 2023-06-21 01:02:05.079 ERROR (MainThread) [custom_components.peaqev.peaqservice.hub.max_min_controller] Encountered problem when trying to reset max charge to normal: could not convert string to float: 'unavailable'
> ```

_these are weird and not good, but can't see them realted to Garo but to your powersensor of choice. They have to be addressed_
> 
> Last time I got the impression that there were more errors in develop compared to the older garo_wallbox. And that it was difficult to get peaqev to go to Start and start charging. But I'm not sure, maybe it is the same, and the main problem I have might be that in many use cases it is necessary to reload the integration to get it out of the "running" state so that it will do a second start charging.
> 

_Ok, not satisfied with this then. The turning off must be working otherwise people won't dare to use it. So good that you mention it._

> I will hopefully learn more as I continue using it.
> 
> A problem with Garo is that it takes very long for the 'charging power' and 'charging current' sensors to go to zero when charging is stopped. For Garo it would be better to track 'active' by checking the state. The state goes to "charging disabled" a lot quicker than power and current goes to zero.

_This bit should probably be addressed related to #272_

**Comment by elden1337** [comment]
about to push forawrd and release 3.0.0 very soon. have you been beta-testing? is garo working for you now? @joek-makewave

**Comment by joek-makewave** [comment]
Hi, no it is not working for me right know but I do not have the latest. The best results were with first garo branch and older peaqevcore.

I should probably try with the latest hass-peaq, see what happens and try to debug from there if there are problems, when I have some time to fiddle.

**Comment by elden1337** [comment]
Sorry to hear that. 
Yes, given the updates since we'll have to push forward to get it to work rather than rollback.

**Pull request merged**
