### PR TITLE
Garo sensor names, set mode service call

### PR DESCRIPTION
**Pull request by joek-makewave**
Updating senor names and set mode service calls to match the Garo wallbox integration.

### CODE REVIEW

**Comment by elden1337** [comment]
Does this mean that it works for you now?

**Comment by joek-makewave** [comment]
No. The PR should probably have been a draft. It has the easy corrections that I found without too much effort. I'm changing the PR to a draft.

I still have the following repeating in the log. And the `Peaqev Charger controller` state is Error most of the time.

```
2023-05-29 13:37:34.060 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.peaqev_energy_including_car
Traceback (most recent call last):
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/helpers/event.py", line 287, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/components/utility_meter/sensor.py", line 450, in async_reading
    for sensor in self.hass.data[DATA_UTILITY][self._parent_meter][
KeyError: 'utility_meter_data'
2023-05-29 13:37:34.241 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.peaqev_energy_cost_integral
Traceback (most recent call last):
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/helpers/event.py", line 287, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/components/utility_meter/sensor.py", line 450, in async_reading
    for sensor in self.hass.data[DATA_UTILITY][self._parent_meter][
KeyError: 'utility_meter_data'
[]

```

**Comment by elden1337** [comment]
Cool. We'll continue to investigate those reasons. I also have it on the pending Keba-integration so probably something in the generic code that isnt noticeable for chargeamps or easee.

**Comment by joek-makewave** [comment]
I can try to update the `native_chargerstates` in garo_wallbox.py (to lower case and use the current list of states from the Garo Wallbox integration). I can then try to match up states with `ChargeControllerStates`. Anything I should know about the different charge controller states?

Or are you already working on this?

**Comment by elden1337** [comment]
Yeah pause a little. I think there are things in the core-repo i need to fix, and that's a different story ;). 
Getting back as soon as possible.

**Comment by elden1337** [comment]
Hi! 
Can you pull the latest from develop-branch into your fork and try with your changes then? I've made a small update to the core-repo that hopefully should make better use of the attribute-sensor (error state). but we'll see..

**Comment by joek-makewave** [comment]
OK, fresh Homeassistant 2023.5.4 with Garo, Nordpool and Peaqev (garo_wallbox branch with latest from develop). I have a lot of these in the log:
```
2023-06-05 11:35:06.613 ERROR (MainThread) [peaqevcore.models.hub.hubmember] could not set value for sensor.wallbox_charging_current to None of type <class 'int'> because of float() argument must be a string or a real number, not 'NoneType'
```
There is also:
```
2023-06-05 11:35:11.158 WARNING (MainThread) [homeassistant.components.utility_meter.sensor] Peaqev energy_cost_integral daily received an invalid new state from sensor.peaqev_energy_cost_integral : unknown
2023-06-05 11:35:11.164 WARNING (MainThread) [homeassistant.components.utility_meter.sensor] Peaqev energy_cost_integral monthly received an invalid new state from sensor.peaqev_energy_cost_integral : unknown
```
And after a while:
```
2023-06-05 11:37:19.884 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.peaqev_energy_including_car
Traceback (most recent call last):
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/helpers/event.py", line 287, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/components/utility_meter/sensor.py", line 450, in async_reading
    for sensor in self.hass.data[DATA_UTILITY][self._parent_meter][
KeyError: 'utility_meter_data'
```

Everything looks OK in the GUI. Anything I can check there?

**Comment by elden1337** [comment]
Ignore the last one, that's a generic utility meter issue.

**Comment by elden1337** [comment]
sensor.wallbox_charging_current

What does this one report? Is it actually a number or does the problem lie in which sensor we picked?

**Comment by joek-makewave** [comment]
sensor.wallbox_charging_current reports a number.

**Comment by joek-makewave** [comment]
I added logging like this:
```
    def get_sensor_from_hass(self, sensor: str):
        _LOGGER.info(f"get for sensor: {sensor} ...")
```
and got:
```
2023-06-05 14:50:37.668 INFO (MainThread) [peaqevcore.models.hub.hubmember] get for sensor: sensor.wallbox_charging_current|None ...
```
Is it trying to use sensor attribute 'None' instead of sensor state?

**Comment by elden1337** [comment]
Got it. That method should only take the part before |. Ill fix it generically.

**Comment by elden1337** [comment]
;) couldn't charge my own car now with the latest from develop... so don't sweat it ill have a look again.

**Comment by elden1337** [comment]
Now i can. Pull again

**Comment by joek-makewave** [comment]
Some success: Car is plugged in, charging Off in Garo web GUI. When I toggle Peaqev Charger controller to On, Garo service is called to turn charging on and to set limit.

I'm not able to repeat this though. If I turn charging Off in Garo GUI, I can not get Peaqev to turn it on again. If I go to Settings and reload the Peaqev integration, it is possible to get it to turn charging on again, once.

Maybe `GaroWallBox._set_charger_states` needs some tweaking?

**Comment by elden1337** [comment]
Could be that the overtake charger functions in charger.py needs altering. Or the states as you say. 

Did you get any useful logs whilst doing this? Ie, when you altered it outside of peaqev, did peaqev log something? Dont worry about the state of chargecontroller it should still say start in your case if that's the intention of peaqev still. 

Also remember that it could perhaps discard to restart after that because it calcs that youve spent too much energy for the current hour/quarter to start once more right then.

**Comment by elden1337** [comment]
image

In this illustration of the threshold, it will let you start for values below the green line, and then let you continue charging til it reaches the red. 
So if you are in between the lines and not charging atm it will not start.

**Comment by joek-makewave** [comment]
I don't think there is any interesting in the logs from peaqev when I alter the charger from the outside. I can try to test some more and enable debug logging. Right now the "KeyError: 'utility_meter_data'" error spams the logs a bit, is there an easy way for me to get rid of those?

Do you have a description of the different ChargeControllerStates? There are a lot of Garo states, I could try to get a better mapping from Garo to Peaqev state in GaroWallBox._set_charger_states. For instance, there is no mapping to ChargeControllerStates.Stop.

**Comment by elden1337** [comment]
The states that must be mapped are commented with ** here. the ones that can be mapped are *
This might be confusing as i'm using this enum-state for the chargecontroller, but the mapping from each type is just a translator for the demanded types (**).

```python
from enum import Enum

class ChargeControllerStates(Enum):
    Idle = "Idle" **
    Connected = "Connected" **
    Start = "Start"
    Stop = "Stop"
    Done = "Done" *
    Error = "Error, check logs."
    Charging = "Charging" **
    Disabled = "Disabled"
```

Start and Stop are determined in `async def async_get_status(self) -> Tuple[ChargeControllerStates, bool]` in `ichargecontroller.py` depending on the current state of many things (but i need the native states mapped there to determine some of the cases.

I have an idea as to what might be an issue now also. The `istate_changes.py` listens to state-changes for a number of entities added on boot (like the chargerobject), but it does not listen to attribute-changes since those aren't afaik sent as updates through the state machine. Therefore i'm mimicking it by updating the attribute _if applicable_ for that sensor. But, since i'm not getting any changes to the state in question, the internal state of peaqev (from the attribute) is not updated.
I can get around this by adding a time-based polling there if the currently setup chargertype has attributes as sensor-state. I think i'll have to do that.

**Comment by elden1337** [comment]
ill go ahead and spend a little time to try and work around that above issue now

**Comment by elden1337** [comment]
https://github.com/elden1337/hass-peaq/commit/bfff4a210c16c7d068b6a749dc59861577d9ae50

have no idea if this will solve it though, but it should update the state from the attribute more frequently at least.

**Comment by joek-makewave** [comment]
Thanks! I'll do more testing as soon as I have some free time!

**Comment by joek-makewave** [comment]
Still can't get peaqev to start the charger a second time.

Charger controller has 'Start' but in `charger.async_start_case` `self.model.running` is True and no service call is made to start the charger.

If I disable and enable peaqev at this time there are calls to `async_stop_case` but there `self.charger_active` is False so nothing updates.

**Comment by elden1337** [comment]
So process is still that you try to stop it from outside of peaqev and then expect it to start itself again?

But a regular start works, aswell as amp update? 
If you would let it run, does it also stop to not breach peak?

**Comment by joek-makewave** [comment]
Yes. I expect peaqev to start the charger again if/when peaqev is enabled.

I have only managed peaqev to start the charger once after installation/reloading of the peaqev integration. If I stop the charger from the outside, I have not found a way to get peaqev to exit "running" so that it will perform another start.

The first start works, set limit works. I have not been able to try stop at peak yet. The car's battery is almost full at the moment. I will try that.

Maybe a second start will work if peaqev stops by itself. Maybe it is only stopping from the outside that is problematic. I will also test unplugging the car, and letting peaqev charge until the charger reports finished.

I think that there should be a way out if you stop from the outside though. 

Thanks for the support so far!

**Comment by elden1337** [comment]
I think you are hitting a generic corner case that i'm not fully supporting, hence the questions. 

I can look into it but in a separate issue in that case. I think it sounds as if we'r approaching stellar with Garo which is great! I'll await your qa on charging a cycle when you have time and need, but please sit by it the first hour so that i don't break your peak by accident ;).

**Comment by joek-makewave** [comment]
With the latest changes I get the following error. I think I fixed it but you should know to fix it properly.

```
2023-06-09 15:33:35.008 ERROR (MainThread) [custom_components.peaqev.peaqservice.hub.hub] Unable to handle data-update: sensor.peaqev_charger_controller <state sensor.peaqev_charger_controller=unknown; price aware=False, current_hour state=None, scheduler_active=False, icon=mdi:battery, friendly_name=Peaqev Charger controller @ 2023-06-09T13:33:30.927028+00:00>|<state sensor.peaqev_charger_controller=Initializing...; price aware=True, current_hour state=Charging permitted, scheduler_active=False, icon=mdi:battery, friendly_name=Peaqev Charger controller @ 2023-06-09T13:33:35.003125+00:00>. Exception: name 'ChargerType' is not defined
```

I hope to get some testing time later, right now there is no charging before 22:00. Maybe best to turn off price aware.

**Comment by joek-makewave** [comment]
The latest from develop is causing the charger to be repeatedly turned On and Off, most Off.

Pseudo description of what happens based on some logging added by me:
* getting state from Garo: 'charging disabled' or 'charging'
* reset session
* Charger.controller.status_type is Stop
* charger_active in stop_case()
* async_pause_charger()
* Garo service is called to set mode to Off

This repeats but next time Charger.controller.status_type is Start. Most of the time we are "running" and "active" so no Garo service call to On. Next is a Stop case and another Garo service call with Off. Some times a Start leads to "Restarting charger ..." but sequence above keeps repeating and there are new Garo calls to Off, and sometimes On.

**Comment by joek-makewave** [comment]
After a restart of hass, the repeating loop is now:

* getting state 'charging' form Garo
* reset session
* status_type is Start
* Restarting charger since it has been turned off ...
* Garo service called with On

This works, Garo keeps charging. The "Restarting" bit is not true but that might not be important?

I'll let it charge to see what happens when the battery is full.

**Comment by joek-makewave** [comment]
After about 9 minutes (also after the first set limit call), status_type = Start and start_case() do no longer try do the restarting bit since we are running and active. This is even better. Did set limit somehow finally align peaqev state to the Garo state?

**Comment by elden1337** [comment]
Hahaha. Ok. Back to work

**Comment by elden1337** [comment]
it sounds to me as if we'r still lacking the status updates from those attributes to be honest. the weird behaviour of it calling so often must of course be addressed by me, but imo if it could read the proper state if shouldn't continue to loop in that way but wait for new instructions... as said earlier, i have to look more.

**Comment by elden1337** [comment]
but unless you pull latest from develop now it's broken in ha 2023.6.1 anyways fyi, same as affected main that i just released hotfix for.

**Comment by elden1337** [comment]
Now all sensors that use attributes should fetch latest from HA on getting the connected peaqev-sensor. Ie not bound to the state_changes as I think those were too slow in this usecase.

**Comment by elden1337** [comment]
and now i've made sure i have no known hickups with develop branch at my machine again (had some with my own chargerstate after the changes yesterday)

**Comment by elden1337** [comment]
tbh i think this pr is ready for review.

**Comment by joek-makewave** [comment]
It has been working fairly well during some recent testing. I have seen the following error a couple of times. It repeats but is gone after a restart of homeassistant. Is it running without price aware that causes this?
 
I include the extra logging added by me, it might make it clearer what is happening.
```
2023-06-11 00:24:19.552 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.ichargecontroller] 1 got sensor data state charging finished
2023-06-11 00:24:19.552 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.ichargecontroller] 2 status is ChargeControllerStates.Done, update_timer is False
2023-06-11 00:24:19.553 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.ichargecontroller] 3 model status_type from Start to Done
2023-06-11 00:24:19.553 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.charger.charger] 4 Charge done_idle_case() (ChargeControllerStates.Done)
2023-06-11 00:24:19.554 INFO (MainThread) [custom_components.peaqev.peaqservice.hub.state_changes.istate_changes] update on sensor.wallbox_status, calling charge
2023-06-11 00:24:19.554 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.charger.charger] 4 Charge done_idle_case() (ChargeControllerStates.Done)
2023-06-11 00:24:19.557 INFO (MainThread) [custom_components.garo_wallbox.sensor] mode: Off
2023-06-11 00:24:19.659 INFO (MainThread) [custom_components.peaqev.peaqservice.hub.state_changes.istate_changes] update on sensor.wallbox, calling charge
2023-06-11 00:24:19.659 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.charger.charger] 4 Charge done_idle_case() (ChargeControllerStates.Done)
2023-06-11 00:24:20.015 INFO (MainThread) [custom_components.peaqev.peaqservice.hub.state_changes.istate_changes] update on sensor.peaqev_charger_controller, calling charge
2023-06-11 00:24:20.015 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.charger.charger] 4 Charge done_idle_case() (ChargeControllerStates.Done)
2023-06-11 00:24:20.016 INFO (MainThread) [custom_components.peaqev.peaqservice.hub.state_changes.istate_changes] update on sensor.peaqev_average_consumption, calling charge
2023-06-11 00:24:20.017 INFO (MainThread) [custom_components.peaqev.peaqservice.chargecontroller.charger.charger] 4 Charge done_idle_case() (ChargeControllerStates.Done)
2023-06-11 00:24:20.055 ERROR (MainThread) [custom_components.peaqev.peaqservice.hub.max_min_controller] Encountered problem when trying to reset max charge to normal: could not convert string to float: 'unavailable'
2023-06-11 00:24:20.057 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/jonas/git/hass-peaq/custom_components/peaqev/peaqservice/hub/observer/observer_coordinator.py", line 69, in async_dispatch
    await self.async_dequeue_and_broadcast(q)
  File "/Users/jonas/git/hass-peaq/custom_components/peaqev/peaqservice/hub/observer/observer_coordinator.py", line 79, in async_dequeue_and_broadcast
    await self.async_call_func(func=func, command=command),
  File "/Users/jonas/git/hass-peaq/custom_components/peaqev/peaqservice/hub/observer/observer_coordinator.py", line 116, in async_call_func
    await func(command.argument)
  File "/Users/jonas/git/hass-peaq/custom_components/peaqev/peaqservice/chargecontroller/charger/savings_controller.py", line 81, in async_exit
    await self.service.async_register_charge_session(
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/peaqevcore/services/savings/savings_service.py", line 82, in async_register_charge_session
    simulated_cost = await self.async_direct_charge_cost(
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/peaqevcore/services/savings/savings_service.py", line 123, in async_direct_charge_cost
    ret += min(total_energy, power_key) * self.model.prices[dt.date()][dt.hour]
IndexError: list index out of range```

**Comment by joek-makewave** [comment]
There is one serious problem though. I had to change one of the states in the Garo integration. 

Status.SEARCH_COMM should be "Vehicle not connected" and not "Vehicle connected". There is a Garo pull request for this fix, https://github.com/sockless-coding/garo_wallbox/pull/23.

**Comment by elden1337** [comment]
Yeah those are unrelated bugs, thanks for noticing. 

And i have now commented out the quickfix to start again if stopped elsewhere fyi. 

So what we need to make sure is that your charger can be started from peaq, stopped whenever peak is being reached (chargecontroller says stop) and that it can update the amps. 

If u feel satisfied with those cases i think we can call it mergable!

**Comment by joek-makewave** [comment]
I think I liked the restarting thing. But we can start with what you say and I will do some more testing.

Are you okey with all the merging in this PR? I can make a new one with only the changes to garowallbox.py if that is better.

Can you add a note somewhere about the Garo integration fix for state SEARCH_COMM?

**Comment by elden1337** [comment]
If the actual changes are merely the ones in garo-files it's perhaps easiest to make a new pr. 

I didnt like that it called your charger so extremely often with that change, thus i removed it for now cos need to do it with some throttleing. 

- But in bed now so no rush, thanks for chippng in and hope it helps you charge cheaper! ;)

**Comment by joek-makewave** [comment]
I made a new branch and PR that only have the changes in garowallbox.py. I'm not sure how well it will work with current main, I think you made some changes for Garo in the develop branch of hass-peaq and some in peaqevcore.

New PR: #270

**Comment by elden1337** [comment]
thanks a lot! will review and merge to dev.

**Pull request closed without merging**
